<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Test URL Shortener Service">
    <link rel="icon" href="favicon.ico">

    <title>Test URL Shortener Service</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <link href="assets/css/style.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">

       <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Test url shortener</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <div class="jumbotron">
		  <form id="form1">
			<h2>Paste your URL here:</h2>
			<div class="input-group">
				<label for="url" class="sr-only">Paste a link to shorten it</label>
				<input type="url" id="url" class="form-control" placeholder="http://example.com" required autofocus>
				<span class="input-group-btn">
					<button id="shorten-btn" class="btn btn-primary" type="submit">Shorten</button>
				</span>
			</div>
		  </form>
      </div>

			<div id="result" class="container-fluid">
				<p class="text-center separator" ><span>Shortlink created</span></p>
				<div class="row">
					<div class="col-xs-6 col-md-4">
						<p class="text-center"><img id="result-img" src="" alt="Generated by WebThumbnail.org" /></p>
					</div>
					<div class="clearfix visible-xs-block"></div>
					<div class="col-xs-6 col-md-4">
						<p>
						<input type="surl" id="surl" class="form-control" value="" autocomplete="off" autocorrect="off" autocapitalize="off">
						</p>
						<p><a id="result-url" href="#" target="blank"></a></p>
						<p>Created: <span id="result-created"></span> ago</p>
						<p>Total Clicks: <span id="result-clicks">0</span></p>
					</div>
					<div class="clearfix visible-xs-block"></div>
					<div class="col-xs-6 col-md-4">
						<p class="text-center"><img id="result-qr" alt="QR code" src=""></p>
					</div>
				</div>
			</div>
		  </div>
		</div>

    </div><!-- /.container -->

<div id="error-msg" class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>Error!</strong> <span id="error-msg-text"></span>
</div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="assets/js/ie10-viewport-bug-workaround.js"></script>

    <script src="assets/js/api.js"></script>
  </body>
</html>
